### ISSUE TITLE
Chainload for win7 and non-legacy grub may seems to be not right for a pure UEFI-setup

### ISSUE THREAD

**Issue by dakewingduck** [funtoo/boot-update#8]
Hello,
When using a UEFI-Mainboard with a UEFI-Installation of Win7 and Funtoo, boot-update does not generate the correct Windows7 Section in the grub.cfg.
As displayed in line 73 of boot-update/python/modules/funtoo/boot/extensions/grub.py
it generates "  chainloader +4", while at least in my setup 
"chainloader /EFI/Microsoft/Boot/bootmgfw.efi"
is needed to boot the UEFI-Installation of Windows 7.

I would be more then satisfied for a response and an alteration of the code to support a pure UEFI-Setup.

If needed I will provide more Information.
Thank you for your attention and your hard work.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2860

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
